(TeX-add-style-hook "contraportada"
 (lambda ()
    (TeX-run-style-hooks
     "pifont"
     "hyperref"
     "marvosym"
     "wasysym"
     "tikz"
     "xcolor"
     "table"
     "svgnames"
     "dvipsnames"
     "usenames"
     "fontenc"
     "T1"
     "venturis2"
     "inputenc"
     "utf8"
     "babel"
     "portuguese"
     "latex2e"
     "scrartcl10"
     "scrartcl"
     "")))

